/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DhoAmbulanceWlList {
    }
}
declare global {
    interface HTMLDhoAmbulanceWlListElement extends Components.DhoAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLDhoAmbulanceWlListElement: {
        prototype: HTMLDhoAmbulanceWlListElement;
        new (): HTMLDhoAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "dho-ambulance-wl-list": HTMLDhoAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface DhoAmbulanceWlList {
    }
    interface IntrinsicElements {
        "dho-ambulance-wl-list": DhoAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dho-ambulance-wl-list": LocalJSX.IntrinsicElements["dho-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLDhoAmbulanceWlListElement>;
        }
    }
}
