/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DhoAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
    }
    interface DhoAmbulanceWlEditor {
        "ambulanceId": string;
        "apiBase": string;
        "entryId": string;
    }
    interface DhoAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface DhoAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDhoAmbulanceWlEditorElement;
}
export interface DhoAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDhoAmbulanceWlListElement;
}
declare global {
    interface HTMLDhoAmbulanceWlAppElement extends Components.DhoAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLDhoAmbulanceWlAppElement: {
        prototype: HTMLDhoAmbulanceWlAppElement;
        new (): HTMLDhoAmbulanceWlAppElement;
    };
    interface HTMLDhoAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLDhoAmbulanceWlEditorElement extends Components.DhoAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDhoAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLDhoAmbulanceWlEditorElement, ev: DhoAmbulanceWlEditorCustomEvent<HTMLDhoAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDhoAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLDhoAmbulanceWlEditorElement, ev: DhoAmbulanceWlEditorCustomEvent<HTMLDhoAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDhoAmbulanceWlEditorElement: {
        prototype: HTMLDhoAmbulanceWlEditorElement;
        new (): HTMLDhoAmbulanceWlEditorElement;
    };
    interface HTMLDhoAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLDhoAmbulanceWlListElement extends Components.DhoAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDhoAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLDhoAmbulanceWlListElement, ev: DhoAmbulanceWlListCustomEvent<HTMLDhoAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDhoAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLDhoAmbulanceWlListElement, ev: DhoAmbulanceWlListCustomEvent<HTMLDhoAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDhoAmbulanceWlListElement: {
        prototype: HTMLDhoAmbulanceWlListElement;
        new (): HTMLDhoAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "dho-ambulance-wl-app": HTMLDhoAmbulanceWlAppElement;
        "dho-ambulance-wl-editor": HTMLDhoAmbulanceWlEditorElement;
        "dho-ambulance-wl-list": HTMLDhoAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface DhoAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
    }
    interface DhoAmbulanceWlEditor {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: DhoAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface DhoAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: DhoAmbulanceWlListCustomEvent<string>) => void;
    }

    interface DhoAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface DhoAmbulanceWlEditorAttributes {
        "entryId": string;
        "ambulanceId": string;
        "apiBase": string;
    }
    interface DhoAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }

    interface IntrinsicElements {
        "dho-ambulance-wl-app": Omit<DhoAmbulanceWlApp, keyof DhoAmbulanceWlAppAttributes> & { [K in keyof DhoAmbulanceWlApp & keyof DhoAmbulanceWlAppAttributes]?: DhoAmbulanceWlApp[K] } & { [K in keyof DhoAmbulanceWlApp & keyof DhoAmbulanceWlAppAttributes as `attr:${K}`]?: DhoAmbulanceWlAppAttributes[K] } & { [K in keyof DhoAmbulanceWlApp & keyof DhoAmbulanceWlAppAttributes as `prop:${K}`]?: DhoAmbulanceWlApp[K] };
        "dho-ambulance-wl-editor": Omit<DhoAmbulanceWlEditor, keyof DhoAmbulanceWlEditorAttributes> & { [K in keyof DhoAmbulanceWlEditor & keyof DhoAmbulanceWlEditorAttributes]?: DhoAmbulanceWlEditor[K] } & { [K in keyof DhoAmbulanceWlEditor & keyof DhoAmbulanceWlEditorAttributes as `attr:${K}`]?: DhoAmbulanceWlEditorAttributes[K] } & { [K in keyof DhoAmbulanceWlEditor & keyof DhoAmbulanceWlEditorAttributes as `prop:${K}`]?: DhoAmbulanceWlEditor[K] };
        "dho-ambulance-wl-list": Omit<DhoAmbulanceWlList, keyof DhoAmbulanceWlListAttributes> & { [K in keyof DhoAmbulanceWlList & keyof DhoAmbulanceWlListAttributes]?: DhoAmbulanceWlList[K] } & { [K in keyof DhoAmbulanceWlList & keyof DhoAmbulanceWlListAttributes as `attr:${K}`]?: DhoAmbulanceWlListAttributes[K] } & { [K in keyof DhoAmbulanceWlList & keyof DhoAmbulanceWlListAttributes as `prop:${K}`]?: DhoAmbulanceWlList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dho-ambulance-wl-app": LocalJSX.IntrinsicElements["dho-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLDhoAmbulanceWlAppElement>;
            "dho-ambulance-wl-editor": LocalJSX.IntrinsicElements["dho-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLDhoAmbulanceWlEditorElement>;
            "dho-ambulance-wl-list": LocalJSX.IntrinsicElements["dho-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLDhoAmbulanceWlListElement>;
        }
    }
}
